### ISSUE TITLE
add unsubscribe option as well as confirm subscription

### ISSUE THREAD

**Issue by anantshri** [infosec-au/websec-weekly#1]
as of now there is no confirm subscription which could lead to spam situation as the person would be totally unaware of subscription till first email lends to it.

would also suggest unsubscribe option.

**Comment by infosec-au** [comment]
Thanks buddy, that's absolutely true and I'll be working on this issue throughout this week. Appreciate the heads up :hamster:

**Comment by anantshri** [comment]
Just now saw, you already have unsubscribe option.

**Comment by infosec-au** [comment]
At the moment, I won't be adding a confirmation for new subscribers. This is because it is too much work to do at the moment. If I move to a more managed transactional API in the future (i.e. [Mandril](https://mandrill.com/)) rather than AmazonSES, this feature will be easy peasy and implemented.
