### ISSUE TITLE
use base64 images instead of linking to website

### ISSUE THREAD

**Issue by anantshri** [infosec-au/websec-weekly#2]
I would suggest using base64 version of various images (company logo's etc) instead of linking it to your website. Might cause a concern as a query would be sent from public IP of user to your website.

I know far fetched thought but might just make sense if you have high number of subscriber as well as just to be on clear.

**Comment by infosec-au** [comment]
Thanks for the suggestion. At the moment, all Gmail users won't experience this problem since all images are re-routed through Google's own HTTPs proxy. I'll implement this when I get the time (hopefully soon).

**Comment by infosec-au** [comment]
This issue has now been fixed :) Sorry it took so long, but thank you for your support and this report.
